on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          goos: ${{ matrix.goos  }}
          goarch: ${{ matrix.goarch  }}
          goversion: "https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz"
          project_path: "./cmd"
          binary_name: "pancake"
          ldflags: "-X main.Version=${{ env.RELEASE_VERSION }}"
          extra_files: README.md
