on: 
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
            echo $RELEASE_VERSION
            echo ${{ env.RELEASE_VERSION }}
#    - uses: actions/checkout@v2
#    - uses: wangyoucao577/go-release-action@v1.14
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN  }}
#        goos: ${{ matrix.goos  }}
#        goarch: ${{ matrix.goarch  }}
#        goversion: "https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz"
#        project_path: "./cmd"
#        binary_name: "pancake"
#        ldflags: "-X main.Version=${{ github.ref }}"
#        extra_files: README.md

